'use client';
import useScrollButton from '@/components/usescrollbutton';
import Link from 'next/link';
import Footer from '@/components/footer';
import Help from '@/components/help';
import { SyncLoader } from 'react-spinners';
import React, { useState ,useEffect } from "react";

const ConfigurePreferences = () => {
    const { showButton, backToTop, isFixed } = useScrollButton();
    const [loading, setLoading] = useState(true);
    const [fadeOut, setFadeOut] = useState(false);
  
    useEffect(() => {
      const timer = setTimeout(() => {
        setFadeOut(true); 
        setTimeout(() => setLoading(false), 500); 
      }, 300); 
      return () => clearTimeout(timer);
    }, []);
  
    if (loading) {
      return (
        <div className={`preloader ${fadeOut ? 'fade-out' : ''}`}>
          <SyncLoader color="#1163ea" size={20} />
        </div>
      );
    }
    return (
        <div className='product'>
            <div className="inner-page">
                <nav className="navbar">
                    <ul className="list-unstyled row mb-0">
                    <li><Link href="/">Home</Link></li>
                        <li><Link href="../../product-document">Article Products</Link></li>
                        <li><Link href="../sdmstroublearticle">SDMS Articles</Link></li>
                    </ul>
                </nav>
            </div>
            <div className='troble-article-list'>
                {showButton && (
                    <button id="btn-back-to-top" onClick={backToTop} style={{ display: 'block' }}>
                        <i className="fas fa-arrow-up"></i>
                    </button>
                )}

  <div className='inner-details'>
                    <h1>Logilab SDMS Settings</h1>
                    <section className='articel-content'>
                    <h3>1.Preferences</h3>
                    <p>To configure Preferences, follow these steps</p>
                    <p className='text-left'>1.On the main menu, click   <img  src='../../image/articel/SDMS/setings.png'  className='m-0 p-0'/> , and then click Preference. The screen appears as shown in the figure:</p>
                        <h4 className='inner-image'>
                         <img  src='../../image/articel/SDMS/Picture56.png'  className='my-3 p-0 '/> 
                        </h4>
                        <p className='figure mt-1'>FIGURE: Preferences Screen</p>
                        <p> 2.In the <b>File View Extension</b> field, click to check the file extensions from the list. The system supports viewing, uploading and downloading of files that are enabled here</p>
                        <p>3.Fill in all other fields and then click <b>Submit </b>to save the settings.</p>
                        <p>4.Click <b>Reset</b> to clear all fields for fresh entry if required..</p>
                        <p>The administrator can use the Preference screen to setup the following:</p>
                        <h2 className='text-left'>Email alerts</h2>
                        <p className='text-left'>Email alerts are emails generated by an automated process and sent to designated recipients. These actions consist of the standard text and list of recipient</p>
                        <p>In the <b>Preference</b> screen, if Enable <b>Email Option</b> is checked, then email alerts are sent for the following scenarios in the server:</p>
                        <ul>
                            <li className='circle mx-4'>When a file version is changed</li>
                            <li className='circle mx-4'>An error occurs while uploading a file</li>
                            <li className='circle mx-4'>When a file is deleted</li>
                        </ul>
                        <p>Type the email id and password from which the mail alert has to be sent. Add recipient mail ids in the To box and <b>CC </b>and <b>Bcc</b> boxes and other fields as applicable.</p>
                        <h2 className='text-left'>Enable Server File Version Delete Policy</h2>
                        <p>Every time a user updates, restores or uploads a new version of an existing file, a new version of the file is created as well as a history of actions for each file</p>
                        <p>To avoid a storage issue, you can define the number of latest versions of the file before permanently deleting the older versions automatically. </p>
                        <p>In the <b>Enable Server File Version Delete Policy</b> field, if you type 5, then latest 5 versions of the files are retained and all older versions are deleted automatically.</p>
                        <h2 className='text-left'>Idle Timeout</h2>
                        <p>When this setting is configured, application logs out automatically after a specified period of inactivity. The default value for idle time-out is 60 minutes.</p>
                        <h2 className='text-left'>Merge File Count</h2>
                        <p>When files are generated by instruments in SDMS, after the specified number of files in <b>Merge File Count</b> field is collected, the files are uploaded to the server / given location. For example, if the<b>Merge File Count</b>  is 5, then after five files are collected, the same is uploaded to the server.</p>
                            <p><b>Note:</b> In the <b>Merge File Count </b>field, you can type a number up to five digits. </p>
                         <h2 className='text-left'>Download Link Logoff (Minutes)</h2>
                         <p>The link shared in the <b>Server Data - File Information </b>tab to view the file for other users, will expire in number of minutes specified in the <b>Download Link Logoff (Minutes)</b> field. For example, if Download Link Logoff (Minutes) is 5, then the shared link expires in five minutes.</p> 

                        <h2 className='text-left'>LIMS Order Display</h2>
                        <p> OrderID and BatchID should appear here. Only then on integration of ELN and LIMS with SDMS you can select and process orders in the Instrument Lock and Tag screen as shown in the figure:</p>
                        <h4 className='inner-image'>
                        <img  src='../../image/articel/SDMS/Picture58.png ' className='my-3 p-0' /> 
                        </h4>
                        <p className='figure mt-1'>FIGURE: LIMS Order Display Option</p>
                        <h2 className='text-left'>Scheduler Rights </h2>
                        <p>When this option enabled, user can define access rights for the scheduler tasks in the User Management-Scheduler Rights tab.</p>
                        <h3>1.2License Information</h3>
                        <p>1.On the main menu, click, <img  src='../../image/articel/SDMS/setings.png' className='mx-2 w-auto'/>  and then click <b>License Information.</b> The screen appears as shown in the figure:</p>
                        <h4 className='inner-image'>
                        <img  src='../../image/articel/SDMS/Picture137.png ' className='my-3 p-0 w-100'/> 
                        </h4>
                        <p className='figure mt-1'>FIGURE:- License Information Screen</p>
                        <p><b>Occupied License</b> denotes number of instruments used or added</p>
                        <p><b>Available License</b> denotes number of instruments shall be added</p>
                        <p>Click <b>Print</b> to preview and print license information</p>
                        <p>Click <b>Export</b> to export license information to Excel.</p>
                        <h3>Setup Work Flow</h3>           
                        <p>Workflows can be designed based on logic in each stage. For example, the data captured from an instrument shall pass through the following stages in a workflow:</p>

                        <table className="table table-bordered">
                            <thead>
                                <tr>
                                <th scope="col">Workflow Stage</th>
                                <th scope="col">Role Mapped</th>
                                <th scope="col">Workflow Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                <th scope="row">Assign</th>
                                <td>Analyst</td>
                                <td>Reviewed</td>
                                </tr>
                                <tr>
                                <th scope="row">Analyze</th>
                                <td>Data Analyst</td>
                                <td>TAnalysis Completed</td>
                                </tr>
                                <tr>
                                <th scope="row">Verify</th>
                                <td>QC</td>
                                <td>Verified</td>
                                </tr>
                                <tr>
                                <th scope="row">Approve</th>
                                <td>QC Manager</td>
                                <td>Approved</td>
                                </tr>
                            </tbody>
                      </table>
                    <p>Each stage in the workflow is mapped to a role. Once the data pass through a stage, the status of the data/file is changed to the next status. The data/file should pass through all the stages in the workflow to successfully complete the job.</p>
                    <p>You can design work flow by adding user groups to each work flow stage.</p>
                    <p>1.On the main menu click,<img  src='../../image/articel/SDMS/setings.png' className='mx-2 w-auto'/> and then click <b>Workflow Setup.</b> The screen appears as shown in the figure:</p>
                    <h4 className='inner-image'>
                    <img  src='../../image/articel/SDMS/Picture110.png'  className='p-0 my-3 w-75'/> 
                   </h4>
                <p className='figure mt-1 p-0'>FIGURE:- Work Flow Setup Screen</p>
                <p>You can see the list of existing work flow steps on the left panel. </p>
                <p>To create a new work flow, follow these steps:</p>
                <p>2.In the <b>Work Flow Step</b> box, the current Workflow Step name selected is displayed.</p>
                <p>3.Under <b>User Group Name </b>box, click to select the user group for the selected work flow step.</p>
                <p>4.Set Workflow for each step by selecting respective User Group Name.</p>
                <p>5.Click <b>Save.</b></p>
                <h3>4.Audit Trail Configuration</h3>
                <p>Audit Trail Configuration screen helps you to configure audit trail. Also enables you to filter records based on specified duration, user and module name, export records to excel file, print records, create archive and open archive to view.</p>
                <p> To view audit trail log, follow these steps:</p>
                <p>1.On the main menu, click  <img  src='../../image/articel/SDMS/setings.png' className='mx-2 w-auto'/>and then click <b>Audit Trail Configuration.</b> The <b>Audit Trail Configuration </b>screen appears as shown in the figure:</p>
                <h4 className='inner-image'>
                    <img  src='../../image/articel/SDMS/Picture138.png'  className='p-0 my-3 w-100'/> 
                   </h4>
                <p className='figure mt-1 p-0'>FIGURE: 109 - Audit Trail Configuration Screen</p>
                <p>You can configure audit trail for tasks in the selected screen. To do so, follow these steps</p>
                <p>2.In the <b>Audit Trail Configuration </b>screen, you can see list of <b>Module Name, Screen Name</b> and then the <b>Tasks</b> in the screen</p>
                <p>3.To configure audit trail for a task, click to select respective check under <b>Manual Audit Trial</b> and then click <b>Save.</b> The E-Signature window will prompt for user name and password while completing that particular task.</p>
                <p>4.Same way, you can configure audit trail for tasks in the other screens.</p>
                <h3>5.SQL Database Log Maintenance</h3>
                <p>When SDMS is connected to SQL server, the SQL Database Log Maintenance screen enables you to clear the SQL log.</p>
                <p> To clear SQL log manually, follow these steps:</p>
                <p>1.On the main menu, click <img  src='../../image/articel/SDMS/setings.png' className='mx-2 w-auto'/> and then click <b>Maintenance.</b> The <b>SQL Database Log Maintenance</b> screen appears as shown in the figure:</p>

                <h4 className='inner-image'>
                    <img  src='../../image/articel/SDMS/Picture139.png'  className='p-0 my-3 '/> 
                   </h4>
                <p className='figure mt-1 p-0'>FIGURE:- SQL Database Log Maintenance Screen</p>
                <p>2.Click Shrink. Wait un till the log is cleared. </p>
                <p>3.You will see a message as shown in the figure:</p>
                <h4 className='inner-image'>
                    <img  src='../../image/articel/SDMS/Picture140.png'  className='p-0 my-3'/> 
                   </h4>
                <p className='figure m-0 p-0'>FIGURE:- SQL Log Cleared -Message</p>
                     </section>
                     <div className='prevartical '>
                    <div className='row my-5'>
                        <div className='col-6 text-left'>
                            <h4>Previous article</h4>
                            <Link href='../clearsql'>How to clear SQL log</Link>
                        </div>
                        <div className='col-6 text-right'>
                            <h4>Next article</h4>
                            <Link href='../workflow'>How to setup work flow in SDMS</Link>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
                <Help/>        
        </div>
    );
}

export default ConfigurePreferences; 