import type { Metadata } from "next";
import Head from "next/head";
import { Inter } from "next/font/google";
// import "public/assets/css/style.css"
import "public/assets/css/vendor/fontawesome-all.min.css";
import "public/assets/css/plugins/swiper.min.css";
import "public/assets/css/plugins/animate-text.css";
import "public/assets/css/plugins/animate.min.css";
import "public/assets/css/plugins/lightgallery.min.css";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css'; 
import Header from '../components/header';
import Footer from "@/components/footer";
import Footertop from "@/components/footertop";
import Help from "@/components/help";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Agaramtech | Helpcenter",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        {/* <link rel="icon" href="/assets/images/favicon.webp" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#000000" />
        <meta
          name="description"
          content="Web site created using create-react-app"
        />
        <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
        <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
        <link rel="icon" href="../../assets/images/favicon.webp" type="image/webp" />
        <link rel="icon" href="../assets/images/favicon.webp" type="image/webp" />
        <link rel="icon" href="/assets/images/favicon.webp" type="image/webp" />
        <link rel="icon" href="assets/images/favicon.webp" type="image/webp" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800;900&display=swap" rel="stylesheet" />


        <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800&display=swap" rel="stylesheet" />
        <title>Agaramtech | Helpcenter</title>
  
      </head>
      <body className={`${inter.className}`}>
        <Header />
        {children}
        {/* <Help/> */}
        {/* <Footertop/> */}
        <Footer/>
      </body>
    </html>
  );
}
